name: flutter_geokit
description: A Flutter package for handling GeoJSON, GeoPackage, and Shapefiles.
version: 0.1.5
homepage: https://algamesh.com
repository: https://github.com/algamesh/flutter_geokit
issue_tracker: https://github.com/algamesh/flutter_geokit/issues
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
